### ISSUE TITLE
Cargo build takes significantly longer time in solbuild

### ISSUE THREAD

**Issue by malfisya** [getsolus/solbuild#87] opened 2024-03-11 14:43 UTC
When I try to build gnome rust-based apps (snapshot, glycin, loupe) with solbuild, it takes significantly longer time compared without solbuild. There is this long pause (10 min or more) between each steps.

Steps to reproduce: 
1. Using recipe in monorepo, build `glycin` inside solbuild. 
2. Time it and observe pause between each steps.
3. Then build `glycin`  without solbuild. 
4.  Time it and observe pause between each steps.
5. Building`glycin` with solbuild takes longer than without it.

**Comment by GZGavinZhao** [comment] 2024-03-11 14:53
Try putting `unset LD_PRELOAD` in the `environment` section?

**Comment by ermo** [comment] 2024-03-12 21:45
Just a note that I can reproduce this, even when using the `unset LD_PRELOAD` statement in an added `environment: |` section.

<img width="808" alt="solbuild-cargo-zombie-when-building-glycin1" src="https://github.com/getsolus/solbuild/assets/118045/a8792946-6662-4ccb-aa2e-c9ba2d7e1944">

Solbuild appears to be just waiting for ... something and `htop` shows no activity for the solbuild process tree and shows cargo as a zombie.

After a few minutes, the build becomes active again. This keeps happening until the build is done it seems. Not a very good UX/DX.

**Comment by silkeh** [comment] 2024-03-16 12:59
This seems to be caused by [this ninja issue](https://github.com/ninja-build/ninja/issues/2052). It is triggered in these packages because `cargo` spawns an `sccache` daemon, and `ninja` waits for it.

It can't easily be fixed in solbuild, but there is a simple workaround:

```yaml
build      : |
    # Work around for https://github.com/ninja-build/ninja/issues/2052
    sccache --start-server

    %ninja_build
```

**Closed as completed by silkeh** 2024-03-16 12:59 UTC

**Comment by malfisya** [comment] 2024-03-16 16:10
Maybe add the workaround here https://github.com/getsolus/help-center-docs/issues/411
